### ISSUE TITLE
Passing null as the memoryLimit argument in Events.init() causes a null pointer exception

### ISSUE THREAD

**Issue by ohEmily** [scalyr/Scalyr-Java-Client#1]
The [docs](https://github.com/scalyr/Scalyr-Java-Client/blob/master/src/com/scalyr/api/logs/Events.java#L79) for the `memoryLimit` argument suggest we can pass `null`:

```
   * @param memoryLimit If not null, then we limit memory usage (for buffering events to be uploaded)
   *     to approximately this many bytes.
```

But passing null causes an exception when that value is passed to `EventUploader`, which takes an `int`.

**Comment by steve-scalyr** [comment]
Thanks for reporting this! We'll fix it for our next library update.

Steve
