### ISSUE TITLE
Log4j vulnerability action

### ISSUE THREAD

**Issue by SamarpanRai-TomTom** [scalyr/Scalyr-Java-Client#55]
Will the team upgrade log4j dependency based on the released report on it's Critical severity? 

For more info : https://www.kaspersky.com/blog/log4shell-critical-vulnerability-in-apache-log4j/43124/

**Comment by Kami** [comment]
Thanks for bringing this up.

This library doesn't depend on and use log4j (https://github.com/scalyr/Scalyr-Java-Client/blob/master/pom.xml#L55) so it's not affected.

The library uses Apache commons logging library which will only use log4j if available and configured by the user in their application where they use scalyr java client.

```bash
[INFO] --- maven-dependency-plugin:2.8:tree (default-cli) @ scalyr-client ---
[INFO] com.scalyr:scalyr-client:jar:6.0.29-SNAPSHOT
[INFO] +- org.apache.httpcomponents:httpclient:jar:4.3.6:compile
[INFO] |  +- commons-logging:commons-logging:jar:1.1.3:compile
[INFO] |  \- commons-codec:commons-codec:jar:1.6:compile
[INFO] +- org.apache.httpcomponents:httpcore:jar:4.3.3:compile
[INFO] +- junit:junit:jar:4.10:test
[INFO] |  \- org.hamcrest:hamcrest-core:jar:1.1:test
[INFO] +- org.mockito:mockito-all:jar:1.9.5:test
[INFO] \- com.google.guava:guava:jar:19.0:compile
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  9.575 s
[INFO] Finished at: 2021-12-13T17:23:45+01:00
[INFO] ------------------------------------------------------------------------
```

**Comment by jjhart** [comment]
@Kami Shall we mark this issue resolved?

**Comment by Kami** [comment]
Yeah, this can be closed since it doesn't affect this library. Thanks for the reminder.
